const assert=require('node:assert/strict');const {chromium}=require('C:/Users/Caffa/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{const p=await browser.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));const base=process.env.TEST_ORIGIN||'http://127.0.0.1:8766';const go=path=>p.goto(base+path,{waitUntil:'domcontentloaded'});
await go('/accessories/?category=care');await p.waitForSelector('[data-accessory-category=care].active');assert.match(await p.locator('[data-accessory-panel=care]').innerText(),/아직 개발 중입니다/);
await p.locator('[data-accessory-category=adapter]').click();assert.equal(await p.locator('#adapterCount').innerText(),'1');assert.match(await p.locator('#adapterList').innerText(),/Leica/);
await p.locator('[data-accessory-category=memory]').click();await p.locator('#memoryType').selectOption('SD');assert.match(await p.locator('#memoryList').innerText(),/UHS-II/);assert.doesNotMatch(await p.locator('#memoryList').innerText(),/microSD|UHS-I\s|CFexpress/);await p.locator('#memorySearch').fill('렉사 128');assert(Number(await p.locator('#memoryCount').innerText())>0);
await p.locator('[data-accessory-category=plate]').click();assert.equal(await p.locator('#plateList article').count(),48);await p.locator('#plateMore').click();assert.equal(await p.locator('#plateList article').count(),96);await p.locator('#plateSearch').fill('포토클램');assert(Number(await p.locator('#plateCount').innerText())>6);
await p.locator('#plateBrand').selectOption('PhotoClam');const href=await p.locator('#plateList a[href*="/builder/"]').first().getAttribute('href');await go(href);await p.waitForFunction(()=>Boolean(document.querySelector('#plateSelect')?.value));assert.match(await p.locator('#plateCompat').innerText(),/바디|플레이트|규격/);
await go('/compare/?category=memory&a=lexar-kr-2151');await p.waitForSelector('#compareProducts article:not(.is-empty)');assert.match(await p.locator('#compareTable').innerText(),/120/);await p.locator('#compareSearchB').fill('소니');await p.locator('#compareResultsB [data-select-product]').first().click();assert.match(await p.locator('#compareTable').innerText(),/CFexpress/);assert.match(await p.locator('#compareProducts').innerText(),/국내 판매처 표시가/);
await p.locator('#accessoryCompareCategory').selectOption('plate');assert.equal(await p.locator('#compareProducts article.is-empty').count(),2);await p.locator('#compareSearchA').fill('포토클램');await p.locator('#compareResultsA [data-select-product]').first().click();assert.match(await p.locator('#compareTable').innerText(),/플레이트/);assert.doesNotMatch(await p.locator('#compareTable').innerText(),/센서 포맷/);
for(const width of [1440,390]){await p.setViewportSize({width,height:900});for(const path of ['/compare/?category=memory&a=lexar-kr-2151','/accessories/?category=memory','/accessories/?category=plate','/accessories/?category=care']){await go(path);await p.waitForFunction(()=>document.querySelector('#accessoryCompareCategory')?.options.length||Number(document.querySelector('#plateCount')?.textContent)>0);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`${width} ${path}: overflow`);}await p.screenshot({path:`tmp/accessory-expansion/ui-${width}.png`,fullPage:true});}
for(const [route,query] of [['/body/','소니 a7'],['/lens/','캐논 RF']]){await go(route);await p.waitForSelector('[data-product-detail]');await p.fill('#catalogSearch',query);assert(await p.locator('[data-product-detail]').count()>0);}
assert.deepEqual(errors,[]);console.log('PASS accessory tabs, Korean search, card filters, plate paging, estimate transfer, same-category comparisons, deep links and mobile layout');}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
